### ISSUE TITLE
Head Tracker sensor implementation

### ISSUE THREAD

**Issue by shubhamsinghmutualmobile** [mutualmobile/ComposeSensors#38]
1. Write implementation for the [Head Tracker sensor](https://developer.android.com/reference/android/hardware/SensorEvent#sensor.type_head_tracker:) in Android
Reference:
<img width="880" alt="Screenshot 2023-04-12 at 12 20 29 PM" src="https://user-images.githubusercontent.com/89389061/231374828-aee8cb40-f5f4-45d3-be2e-6a9c4c92e45b.png">

2. Update README with the created `rememberHeadTrackerSensorState` function

3. Upload a screenshot/screen recording of the sensor working fine

**Comment by Chandra-Mauli-Sharma** [comment]
I would like to work on this.

**Comment by shubhamsinghmutualmobile** [comment]
Done @Chandra-Mauli-Sharma 👍
