### ISSUE TITLE
Gyroscope Limited Axes sensor implementation

### ISSUE THREAD

**Issue by shubhamsinghmutualmobile** [mutualmobile/ComposeSensors#40]
1. Write implementation for the [Limited Axes Gyroscope](https://developer.android.com/reference/android/hardware/SensorEvent#sensor.type_gyroscope_limited_axes:) sensor in Android
Reference: ![Image](https://user-images.githubusercontent.com/89389061/230579446-d1ca3435-d709-4945-8f1d-b6affcdb4fb1.png)

2. Update README with the created `rememberLimitedAxesGyroscopeSensorState` function

3. Upload a screenshot/screen recording of the sensor working fine

**Comment by Chandra-Mauli-Sharma** [comment]
Hello @shubhamsinghmutualmobile, can you please assign this issue to me? I would like to work on it. Thank you!

**Comment by shubhamsinghmutualmobile** [comment]
Thank you for showing interest in this project @Chandra-Mauli-Sharma. I have assigned this issue to you ✅

**Comment by shubhamsinghmutualmobile** [comment]
Closed with #43
